name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"
env:
  CEF_VERSION: "136.1.6+g1ac1b14+chromium-136.0.7103.114"

jobs:
  test:
    name: Test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            run_on: macos-latest
            cef_arch: macosarm64
          - target: x86_64-linux-gnu
            run_on: ubuntu-latest
            cef_arch: linux64
          - target: x86_64-windows-msvc
            run_on: windows-latest
            cef_arch: windows64
    runs-on: ${{ matrix.run_on }}
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        if: ${{ matrix.run_on != 'windows-latest' }}
        run: script/bootstrap
      - name: Machete
        if: ${{ matrix.run_on == 'macos-latest' }}
        uses: bnjbvr/cargo-machete@main
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.cef
          key: test-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache CEF
        id: cache-cef
        uses: actions/cache@v4
        with:
          path: ~/.local/share/cef_binary_${{ env.CEF_VERSION }}_${{ matrix.cef_arch }}
          key: cef-${{ env.CEF_VERSION }}-${{ matrix.cef_arch }}
      - name: Download CEF
        if: ${{ !steps.cache-cef.outputs.cache-hit }}
        run: |
          mkdir -p $HOME/.local/share
          cargo run -p wef-tool download-cef ~/.local/share
      - name: Set CEF_ROOT
        if: ${{ matrix.run_on != 'windows-latest' }}
        run: |
          echo CEF_ROOT=$HOME/.local/share/cef_binary_${{ env.CEF_VERSION }}_${{ matrix.cef_arch }} >> $GITHUB_ENV
      - name: Set CEF_ROOT on windows
        if: ${{ matrix.run_on == 'windows-latest' }}
        run: |
          echo CEF_ROOT=$HOME\.local\share\cef_binary_${{ env.CEF_VERSION }}_${{ matrix.cef_arch }} >> $env:GITHUB_ENV
      - name: Typo check
        if: ${{ matrix.run_on == 'macos-latest' }}
        run: |
          cargo install typos-cli || echo "typos-cli already installed"
          typos
      - name: Lint
        if: ${{ matrix.run_on == 'macos-latest' }}
        run: |
          cargo clippy -- --deny warnings
      - name: Build test
        run: |
          cargo test --all
